### ISSUE TITLE
没有高亮

### ISSUE THREAD

**Issue by whu-lee** [infinilabs/analysis-pinyin#279]
请问如何才能高亮，我用了highlight，返回结果并没有highlight字段。拼音搜索结果正常，但是就是没有高亮？请问如何解决

**Comment by xinrun0928** [comment]
刚换成这个插件，试了下真的就没有高亮，真服了，又要换成ik，大佬还知道有哪个支持拼音搜索的插件吗

**Comment by medcl** [comment]
ignore_pinyin_offset 参数可以控制的
