### ISSUE TITLE
elasticsearch8.7.0可以使用7.x版本的拼音吗

### ISSUE THREAD

**Issue by xuanyuanbao** [infinilabs/analysis-pinyin#290]
请问一下elasticsearch8.7.0可以使用7.x版本的拼音吗

**Comment by WYJ2601780221** [comment]
建议自己下载别的版本的源码，然后进去修改pom文件，自己编译一个需要的版本。我就自己编译了一个8.8.2的，已经测试过了，可以使用

**Comment by medcl** [comment]
https://github.com/infinilabs/analysis-pinyin/releases/tag/v8.7.0

**Comment by xuanyuanbao** [comment]
> 建议自己下载别的版本的源码，然后进去修改pom文件，自己编译一个需要的版本。我就自己编译了一个8.8.2的，已经测试过了，可以使用

我当时也是下载代码，然后自己用idea编译的
