### ISSUE TITLE
求ES 8.12版本的插件

### ISSUE THREAD

**Issue by yanchaoguo** [infinilabs/analysis-pinyin#297]

**Comment by yanchaoguo** [comment]
[Uploading elasticsearch-analysis-pinyin-8.12.0.zip…]()
我编译好了 需要的拿去

**Comment by medcl** [comment]
这里已经有发布：https://github.com/infinilabs/analysis-pinyin/releases/tag/v8.12.0
@yanchaoguo 请不要在这里 promopt 你编译的版本
